# operations 

In [1]:
import numpy as np

# Create two NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
result_add = a + b  # or np.add(a, b)

# Subtraction
result_sub = a - b  # or np.subtract(a, b)

# Multiplication
result_mul = a * b  # or np.multiply(a, b)

# Division
result_div = a / b  # or np.divide(a, b)

print("Addition:", result_add)
print("Subtraction:", result_sub)
print("Multiplication:", result_mul)
print("Division:", result_div)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [2]:

# Exponentiation
result_exp = np.exp(a)
print("Exponentiation:", result_exp)


Exponentiation: [ 2.71828183  7.3890561  20.08553692]


In [3]:
# Square root
result_sqrt = np.sqrt(a)
print("Square Root:", result_sqrt)


Square Root: [1.         1.41421356 1.73205081]


In [4]:
# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(angles)
cos_values = np.cos(angles)
tan_values = np.tan(angles)

print("Sin:", sin_values)
print("Cos:", cos_values)
print("Tan:", tan_values)


Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [7]:
# Logarithmic functions

a=np.array([1,10,100,1000])
result_log = np.log(a)
result_log10 = np.log10(a)
result_log2 = np.log2(a)

print("Natural Logarithm:", result_log)
print("Base-10 Logarithm:", result_log10)
print("Base-2 Logarithm:", result_log2)


Natural Logarithm: [0.         2.30258509 4.60517019 6.90775528]
Base-10 Logarithm: [0. 1. 2. 3.]
Base-2 Logarithm: [0.         3.32192809 6.64385619 9.96578428]


# matrix multiplication

In [8]:
#matrix multiplication 

import numpy as np

# Create two NumPy arrays representing matrices
A = np.array([[1, 2], [3, 4]])  # 2x2 matrix
B = np.array([[5, 6], [7, 8]])  # 2x2 matrix

# Perform matrix multiplication using np.dot()
result_dot = np.dot(A, B)

# Perform matrix multiplication using @ operator (Python 3.5+)
result_at_operator = A @ B

# Print the results
print("Matrix multiplication using np.dot():")
print(result_dot)

print("\nMatrix multiplication using @ operator:")
print(result_at_operator)


Matrix multiplication using np.dot():
[[19 22]
 [43 50]]

Matrix multiplication using @ operator:
[[19 22]
 [43 50]]


# comparisions 

In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 4, 3])

print(arr1 == arr2)  # [ True False  True]
print(arr1 != arr2)  # [False  True False]


[ True False  True]
[False  True False]


In [10]:
print(arr1 < arr2)   # [False  True False]
print(arr1 <= arr2)  # [ True  True  True]
print(arr1 > arr2)   # [False False False]
print(arr1 >= arr2)  # [ True False  True]


[False  True False]
[ True  True  True]
[False False False]
[ True False  True]


# Array Equality (np.array_equal()):

In [11]:
#Array Equality (np.array_equal()):
#To check if two arrays are exactly equal in shape and elements, use np.array_equal().
arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])

print(np.array_equal(arr3, arr4))  # True


True


In [12]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3,5])

print(np.array_equal(arr3, arr4))  # True

False


# Array-wise Comparison (np.allclose()):

In [13]:
arr5 = np.array([1.000001, 2.000001, 3.000001])
arr6 = np.array([1.0, 2.0, 3.0])

print(np.allclose(arr5, arr6))  # True (default tolerance used)

True


# Comparing Maximum and Minimum Values (np.maximum() and np.minimum()):


In [15]:

#These functions compare corresponding elements of two arrays and return the element-wise maximum or minimum.
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 4, 3])

print(np.maximum(arr1, arr2)) 
print(np.minimum(arr1, arr2)) 

[1 4 3]
[1 2 3]


# Comparing Array with Scalar:

In [16]:
# NumPy allows comparison between an array and a scalar value. The result is an array with the same shape as the original array containing boolean values.

print(arr1 > 2)   # [False False  True]
print(arr1 == 2)  # [False  True False]

[False False  True]
[False  True False]
