# aggregate functions 


In [2]:
"""
array_split: Split an array into multiple sub-arrays
"""
import numpy as np

arr = np.arange(10)
print(arr)
sub_arrays = np.array_split(arr, 3)
print(sub_arrays)


[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [3]:
"""
column_stack: Stack 1-D arrays as columns into a 2-D array.
"""

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.column_stack((a, b))
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
"""
concatenate: Concatenate arrays along a specified axis.

"""

import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)
print("----------------")

b = np.array([[5, 6]])
print(b)
print("-----------")

result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]]
----------------
[[5 6]]
-----------
[[1 2]
 [3 4]
 [5 6]]


In [8]:
"""
diagonal: Return the diagonal of an array.

"""

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal = np.diagonal(arr)
print(diagonal)

[1 5 9]


In [11]:
"""
dsplit: Split array along the third axis.
"""

import numpy as np

arr = np.arange(16).reshape((2, 2, 4))
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
result = np.dsplit(arr, 2)
result

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [13]:
"""
dstack: Stack arrays in sequence along the third axis.
"""

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dstack((a, b))
print(result)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [21]:
"""
hsplit: Split array into multiple sub-arrays horizontally (column-wise).
"""
import numpy as np

arr = np.arange(16).reshape((4, 4))
result = np.hsplit(arr, 2)
result
#result[0].shape
#print(arr.shape)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [22]:
"""
hstack: Stack arrays in sequence horizontally (column-wise).

"""
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


In [24]:
"""
ndarray.item: Get a specific element of an array.
"""
import numpy as np

arr = np.array([1, 2, 3])

item = arr.item(0)

print(item)

1


In [25]:
"""
newaxis: Increase the dimension of the existing array.

"""
import numpy as np

arr = np.array([1, 2, 3])
new_arr = arr[:, np.newaxis]
print(new_arr)


[[1]
 [2]
 [3]]


In [26]:
"""
ravel: Flatten an array into a 1-D array.

"""
import numpy as np

arr = np.array([[1, 2], [3, 4]])
flattened = np.ravel(arr)
print(flattened)


[1 2 3 4]


In [27]:
"""
repeat: Repeat elements of an array.
"""

import numpy as np

arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 3)
print(repeated)

[1 1 1 2 2 2 3 3 3]


In [28]:
"""
reshape: Reshape an array into a specified shape.
"""
import numpy as np

arr = np.arange(6)
reshaped = np.reshape(arr, (2, 3))
print(reshaped)


[[0 1 2]
 [3 4 5]]


In [29]:
"""
resize: Resize an array.
"""

import numpy as np

arr = np.arange(3)
resized = np.resize(arr, (5,))
print(resized)


[0 1 2 0 1]


In [ ]:
"""

"""

In [ ]:
"""

"""

In [ ]:
"""

"""

In [ ]:
"""

"""

In [ ]:
"""

"""

In [ ]:
"""

"""

In [ ]:
"""

"""