# array handlings

In [56]:
arr=np.array([21,22,45,65,87,89]).reshape(2,3)
print("array values\n",arr)
print("array type is = ",type(arr))
print("array id is = ",id(arr))

array values
 [[21 22 45]
 [65 87 89]]
array type is =  <class 'numpy.ndarray'>
array id is =  2840765071984


# transpose

In [57]:
new_arr=arr.T
new_arr

array([[21, 65],
       [22, 87],
       [45, 89]])

# ravel() -> convert to 1d array

In [58]:
flat=new_arr.ravel()
flat

array([21, 65, 22, 87, 45, 89])

# append and concatnate

In [59]:
import numpy as np

# Example matrices
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

# Append matrices vertically (stack row-wise)
appended_matrix = np.concatenate((matrix1, matrix2), axis=0)
print("Appended matrix (vertically):")
print(appended_matrix)


Appended matrix (vertically):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [60]:
import numpy as np

# Example matrices
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

# Append matrices vertically (stack row-wise)
appended_matrix = np.concatenate((matrix1, matrix2), axis=1)
print("Appended matrix (vertically):")
print(appended_matrix)

Appended matrix (vertically):
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

# Example matrices
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

# Append matrices vertically (stack row-wise)
appended_matrix = np.concatenate((matrix1, matrix2), axis=1)
print("Appended matrix (vertically):")
print(appended_matrix)

In [63]:
#append worksi in vectos not in matrix data format

import numpy as np

# Example matrices
matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

appended_matrix = np.append(matrix1,matrix2)
print("Appended matrix (vertically):")
print(appended_matrix)

Appended matrix (vertically):
[1 2 3 4 5 6 7 8]


# insert

In [66]:
arr=np.array([21,22,45,65,87,89])
print("array values\n",arr)
arr=np.insert(arr,1,555)
print("array values\n",arr)

array values
 [21 22 45 65 87 89]
array values
 [ 21 555  22  45  65  87  89]


# delete

In [68]:
arr=np.delete(arr,[1]) 
arr

array([21, 45, 65, 87, 89])

# percentile(arr,percent)

In [77]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])
percentile_50 = np.percentile(data, 50)  # 50th percentile (median)
print("50th percentile:", percentile_50)



50th percentile: 3.0


# unique

In [78]:
import numpy as np

data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5])
unique_values = np.unique(data)
print("Unique values:", unique_values)

Unique values: [1 2 3 4 5]


In [79]:
import numpy as np

data = np.array([[1, 2, 2, 3, 3, 3, 4, 4, 5],[1, 2, 2, 3, 3, 3, 5, 4, 5],[1, 2, 2, 3, 3, 3, 4, 4, 5]])
unique_values = np.unique(data)
print("Unique values:", unique_values)

Unique values: [1 2 3 4 5]


# sqrt

In [80]:
import numpy as np

data = np.array([1, 4, 9, 16, 25])
sqrt_values = np.sqrt(data)
print("Square root values:", sqrt_values)


Square root values: [1. 2. 3. 4. 5.]


# arg sort

In [81]:
#numpy.argsort(): Returns the indices that would sort an array.

import numpy as np

data = np.array([3, 1, 2])
sorted_indices = np.argsort(data)
print("Indices that would sort the array:", sorted_indices)

Indices that would sort the array: [1 2 0]


In [82]:
# arg max 

import numpy as np

data = np.array([3, 1, 2])
max_index = np.argmax(data)
print("Index of the maximum value:", max_index)


Index of the maximum value: 0


In [83]:
import numpy as np

data = np.array([3, 1, 2])
min_index = np.argmin(data)
print("Index of the minimum value:", min_index)


Index of the minimum value: 1


In [84]:
import numpy as np

data = np.array([3, 1, 2])
sorted_data = np.sort(data)
print("Sorted array:", sorted_data)


Sorted array: [1 2 3]


# numpy.ptp(): Returns the range of values (max - min) along an axis.

In [85]:
import numpy as np

data = np.array([3, 1, 2])
range_values = np.ptp(data)
print("Range of values:", range_values)

Range of values: 2


# numpy.searchsorted(): Finds the indices where elements should be inserted to maintain order.

In [86]:
import numpy as np

data = np.array([1, 3, 5])
indices = np.searchsorted(data, 4)
print("Indices to insert 4 to maintain order:", indices)


Indices to insert 4 to maintain order: 2


# aggregate function

In [2]:
"""
array_split: Split an array into multiple sub-arrays
"""
import numpy as np

arr = np.arange(10)
print(arr)
sub_arrays = np.array_split(arr, 3)
print(sub_arrays)


[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [3]:
"""
column_stack: Stack 1-D arrays as columns into a 2-D array.
"""

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.column_stack((a, b))
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
"""
concatenate: Concatenate arrays along a specified axis.

"""

import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)
print("----------------")

b = np.array([[5, 6]])
print(b)
print("-----------")

result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]]
----------------
[[5 6]]
-----------
[[1 2]
 [3 4]
 [5 6]]


In [8]:
"""
diagonal: Return the diagonal of an array.

"""

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal = np.diagonal(arr)
print(diagonal)

[1 5 9]


In [11]:
"""
dsplit: Split array along the third axis.
"""

import numpy as np

arr = np.arange(16).reshape((2, 2, 4))
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [12]:
result = np.dsplit(arr, 2)
result

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [13]:
"""
dstack: Stack arrays in sequence along the third axis.
"""

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dstack((a, b))
print(result)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [21]:
"""
hsplit: Split array into multiple sub-arrays horizontally (column-wise).
"""
import numpy as np

arr = np.arange(16).reshape((4, 4))
result = np.hsplit(arr, 2)
result
#result[0].shape
#print(arr.shape)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [22]:
"""
hstack: Stack arrays in sequence horizontally (column-wise).

"""
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


In [24]:
"""
ndarray.item: Get a specific element of an array.
"""
import numpy as np

arr = np.array([1, 2, 3])

item = arr.item(0)

print(item)

1


In [25]:
"""
newaxis: Increase the dimension of the existing array.

"""
import numpy as np

arr = np.array([1, 2, 3])
new_arr = arr[:, np.newaxis]
print(new_arr)


[[1]
 [2]
 [3]]


In [26]:
"""
ravel: Flatten an array into a 1-D array.

"""
import numpy as np

arr = np.array([[1, 2], [3, 4]])
flattened = np.ravel(arr)
print(flattened)


[1 2 3 4]


In [27]:
"""
repeat: Repeat elements of an array.
"""

import numpy as np

arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 3)
print(repeated)

[1 1 1 2 2 2 3 3 3]


In [28]:
"""
reshape: Reshape an array into a specified shape.
"""
import numpy as np

arr = np.arange(6)
reshaped = np.reshape(arr, (2, 3))
print(reshaped)


[[0 1 2]
 [3 4 5]]


In [29]:
"""
resize: Resize an array.
"""

import numpy as np

arr = np.arange(3)
resized = np.resize(arr, (5,))
print(resized)


[0 1 2 0 1]


In [1]:
"""
squeeze: Remove single-dimensional entries from the shape of an array.
"""
import numpy as np

arr = np.array([[[0], [1], [2]]])
squeezed = np.squeeze(arr)
print(squeezed.shape)
print(squeezed)

(3,)
[0 1 2]


In [4]:
"""
swapaxes: Interchange two axes of an array.
"""
import numpy as np

arr = np.array([[1, 2, 3]])
swapped = np.swapaxes(arr,0,1)
print(swapped)


[[1]
 [2]
 [3]]


In [5]:
"""
take: Return elements from an array along a specified axis.
"""
import numpy as np

arr = np.array([4, 3, 5, 7, 6])
indices = [0, 2, 3]
taken = np.take(arr, indices)
print(taken)


[4 5 7]


In [7]:
"""
transpose: Permute the dimensions of an array.

"""

import numpy as np

arr = np.arange(4).reshape((2, 2))
print(arr)
transposed = np.transpose(arr)
print(transposed)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [9]:
"""
vsplit: Split array into multiple sub-arrays vertically (row-wise).

"""
import numpy as np

arr = np.arange(16).reshape((4, 4))
result = np.vsplit(arr, 2)
result

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [10]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
"""
vstack: Stack arrays in sequence vertically (row-wise).
"""



import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


# aggregate functions 

# sum()

In [14]:
"""
sum
"""

a1=np.arange(1,6)
print(a1)
total=a1.sum()
print(total)

[1 2 3 4 5]
15


In [17]:
a1=np.arange(1,16).reshape((3,5))
print(a1)
total=a1.sum()
print(total)

#column wise addition
total=a1.sum(axis=0)
print(total)

#row wise wise of matrix addition
total=a1.sum(axis=1)
print(total)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
120
[18 21 24 27 30]
[15 40 65]


# min()

In [18]:
a1=np.arange(1,6)
print(a1)
total=a1.min()
print(total)

[1 2 3 4 5]
1


In [21]:
a2=np.arange(1,16).reshape((3,5))
print(a2)
total=a2.min()
print(total)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1


In [22]:
#column wise 
total=a2.min(axis=0)
print(total)

#row wise wise 
total=a2.min(axis=1)
print(total)

[1 2 3 4 5]
[ 1  6 11]


# max()

In [24]:
total=a1.max()
print(total)

5


In [25]:
total=a2.max()
print(total)

15


In [27]:
#column wise 
total=a2.max(axis=0)
print(total)

#row wise wise 
total=a2.max(axis=1)
print(total)

[11 12 13 14 15]
[ 5 10 15]


# cumsum()

In [29]:
total=a1.cumsum()
print(total)

[ 1  3  6 10 15]


In [30]:
total=a2.cumsum()
print(total)

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]


In [31]:
#col
total=a2.cumsum(axis=0)
print(total)

[[ 1  2  3  4  5]
 [ 7  9 11 13 15]
 [18 21 24 27 30]]


In [33]:
#col
total=a2.cumsum(axis=1)
print(total)

[[ 1  3  6 10 15]
 [ 6 13 21 30 40]
 [11 23 36 50 65]]


# mean

In [34]:
total=a1.mean()
print(total)

3.0


In [36]:
total=a2.mean()
print(total)

8.0


In [38]:
#column wise 
total=a2.mean(axis=0)
print(total)

#row wise wise 
total=a2.mean(axis=1)
print(total)

[ 6.  7.  8.  9. 10.]
[ 3.  8. 13.]


# median

In [40]:
total=np.median(a1)
print(total)

3.0


In [41]:
total=np.median(a2)
print(total)

8.0


In [42]:
total=np.median(a2,axis=0)
print(total)

[ 6.  7.  8.  9. 10.]


In [43]:
total=np.median(a2,axis=1)
print(total)

[ 3.  8. 13.]


# standard deviation 

In [44]:
total=np.std(a1)
print(total)

1.4142135623730951


In [45]:
total=np.std(a2)
print(total)

4.320493798938574


In [46]:
total=np.std(a2,axis=1)
print(total)

[1.41421356 1.41421356 1.41421356]


In [47]:
total=np.std(a2,axis=0)
print(total)

[4.0824829 4.0824829 4.0824829 4.0824829 4.0824829]


# correlation coefficient 

In [49]:
import numpy as np

# Example data
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Compute correlation coefficient matrix
correlation_matrix = np.corrcoef(x, y)

print("Correlation coefficient matrix:")
print(correlation_matrix)


Correlation coefficient matrix:
[[ 1. -1.]
 [-1.  1.]]


In [50]:
import numpy as np

# Example data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2.5,6.7,8.5,33.5,5])

# Compute correlation coefficient matrix
correlation_matrix = np.corrcoef(x, y)

print("Correlation coefficient matrix:")
print(correlation_matrix)

Correlation coefficient matrix:
[[1.         0.39782585]
 [0.39782585 1.        ]]


# operations

In [87]:
import numpy as np

choices = [[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23], [30, 31, 32, 33]]
index_array = np.array([0, 2, 3, 1])
result = np.choose(index_array, choices)
print(result)
# Output: [ 0 21 32 13]


[ 0 21 32 13]


In [88]:
arr = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]
result = np.compress(mask, arr)
print(result)
# Output: [1 3 5]


[1 3 5]


In [89]:
arr = np.array([1, 2, 3, 4])
result = np.cumprod(arr)
print(result)
# Output: [ 1  2  6 24]


[ 1  2  6 24]


In [90]:
a = np.array([1, 2])
b = np.array([3, 4])
result = np.inner(a, b)
print(result)
# Output: 11 (since 1*3 + 2*4 = 11)


11


In [91]:
#np.ndarray.fill: This method fills the array with a scalar value. Example:

arr = np.zeros((2, 2))
arr.fill(5)
print(arr)
# Output: [[5. 5.]
#          [5. 5.]]


[[5. 5.]
 [5. 5.]]


In [92]:
#np.product: This function returns the product of array elements over a given axis. Example:

arr = np.array([1, 2, 3, 4])
result = np.product(arr)
print(result)
# Output: 24


24


In [93]:
#np.put: This function replaces specified elements of an array with given values. Example:

arr = np.array([1, 2, 3, 4])
np.put(arr, [0, 2], [-1, -2]) #np.put(arr,indexes, values to place in index)
print(arr)
# Output: [-1  2 -2  4]

[-1  2 -2  4]


In [94]:
#np.putmask: This function changes elements of an array based on conditional statement and values. Example:

arr = np.array([1, 2, 3, 4])
np.putmask(arr, arr > 2, -1)
print(arr)
# Output: [ 1  2 -1 -1]

[ 1  2 -1 -1]


In [95]:
#np.real: This function returns the real part of the complex argument. Example:

arr = np.array([1+2j, 3+4j])
result = np.real(arr)
print(result)
# Output: [1. 3.]

[1. 3.]


In [96]:
#np.sum: This function returns the sum of array elements over a given axis. Example:

arr = np.array([[1, 2], [3, 4]])
result = np.sum(arr)
print(result)
# Output: 10

10


In [98]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array w