# numpy basis

In [ ]:
Learning Objectives

After reading, you should be able to:

Understand the difference between one-, two- and n-dimensional arrays in NumPy
datatypes 
inspecting array 
Initial Placeholders

# inspecting array 

# 1 scalar 

In [54]:
#scalar it has signle quantity has no dimensions (dimension =0)

import numpy as np 

a=20
print("the value of a = ",a)
arr=np.array(a)
print("--------------------------")
print("the value of numpy  a = ",arr)
print("the shape of the array = ",arr.shape)
#print("the length of the array = ",len(arr)) cannnot apply for single values 
print("the dimension of the array = ",arr.ndim)
print("the size of the array = ",arr.size)
print("the data type of the array  = ",arr.dtype)

print("the item size is = ",arr.itemsize)
print("the data of the array = ", arr.data)
t=arr.data
t
print("the name of data type of the array  = ",arr.dtype.name)
print("the as type of array = ",arr.astype(float))


the value of a =  20
--------------------------
the value of numpy  a =  20
the shape of the array =  ()
the dimension of the array =  0
the size of the array =  1
the data type of the array  =  int32
the item size is =  4
the data of the array =  <memory at 0x0000024FADEAD080>
the name of data type of the array  =  int32
the as type of array =  20.0


In [18]:
#scalar it has signle quantity has no dimensions (dimension =0)

import numpy as np 

a=[20]
print("the value of a = ",a)
arr=np.array(a)
print("--------------------------")
print("the value of numpy  a = ",arr)
print("the shape of the array = ",arr.shape)
print("the length of the array = ",len(arr)) 
print("the dimension of the array = ",arr.ndim)
print("the size of the array = ",arr.size)
print("the data type of the array  = ",arr.dtype)

print("the name of data type of the array  = ",arr.dtype.name)
print("the as type of array = ",arr.astype(float))


the value of a =  [20]
--------------------------
the value of numpy  a =  [20]
the shape of the array =  (1,)
the length of the array =  1
the dimension of the array =  1
the size of the array =  1
the data type of the array  =  int32
the name of data type of the array  =  int32
the as type of array =  [20.]


# data types in numpy 

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [20]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [24]:
#int 

import numpy as np

# Creating an integer array
arr_int = np.array([1, 2, 3, 4], dtype=np.int_)
print(arr_int)

[1 2 3 4]


In [25]:
# float 

import numpy as np

# Creating a float array
arr_float = np.array([1.0, 2.5, 3.7], dtype=np.float_)
print(arr_float)


[1.  2.5 3.7]


In [26]:
#complex 

import numpy as np

# Creating a complex array
arr_complex = np.array([1 + 2j, 3 + 4j], dtype=np.complex_)
arr_complex


array([1.+2.j, 3.+4.j])

In [27]:
import numpy as np

# Creating a boolean array
arr_bool = np.array([True, False, True], dtype=np.bool_)
arr_bool


array([ True, False,  True])

In [28]:
import numpy as np

# Creating a string array
arr_str = np.array(['a', 'b', 'c'], dtype=np.str_)
arr_str


array(['a', 'b', 'c'], dtype='<U1')

In [29]:
import numpy as np

# Creating a datetime array

arr_datetime = np.array(['2024-01-01', '2024-02-15'], dtype='datetime64')
arr_datetime

array(['2024-01-01', '2024-02-15'], dtype='datetime64[D]')

In [34]:
import numpy as np

# Creating a timedelta array
arr_timedelta = np.array([1, 2], dtype='timedelta64[D]')
print(arr_timedelta)
arr_timedelta = np.array([1, 2], dtype='timedelta64[h]') # hour
print(arr_timedelta)
arr_timedelta = np.array([1, 2], dtype='timedelta64[m]') # min
print(arr_timedelta)
arr_timedelta = np.array([1, 2], dtype='timedelta64[s]') #sec
print(arr_timedelta)
arr_timedelta


[1 2]
[1 2]
[1 2]
[1 2]


array([1, 2], dtype='timedelta64[s]')

In [36]:
arr=np.array([1,2,3,4], dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# 2 vectors

In [46]:
#vector it has signle direction has one dimension (dimension =1) either row or columns vectors
#in numpy it is neither a row vector nor a column vector by default. It is just a one-dimensional array.
#its dimension is 1

# from list we are making to numpy array 
import numpy as np 

a=[12,15,34,67,32,85]
arr=np.array(a)
#printing a value 
print("the value of a =",a)
print("the type of a = ",type(a))
#printing arr value 
print("the numpy array = ",arr)
print("the type of array =",type(arr))
print("the dimension of the array = ",arr.ndim) #print the dimension of numpy array  #default is row 
print("the shape of the array =",arr.shape) #print the shape of array (row,columns) in tuple format
print("the size of the array = ",arr.size) # print total number of elements present in array 

the value of a = [12, 15, 34, 67, 32, 85]
the type of a =  <class 'list'>
the numpy array =  [12 15 34 67 32 85]
the type of array = <class 'numpy.ndarray'>
the dimension of the array =  1
the shape of the array = (6,)
the size of the array =  6


In [41]:
# from tuple we are making to numpy array 
import numpy as np 

a=(12,15,34,67,32,85)
print("the tuple values = ",a)
arr=np.array(a)
#printing a value 
print("the numpy arrray = ",arr)

the tuple values =  (12, 15, 34, 67, 32, 85)
the numpy arrray =  [12 15 34 67 32 85]


In [42]:
# from set we are making to numpy array 
import numpy as np 

a={12,15,34,67,32,85}

print("the set values = ",a)
arr=np.array(a)
#printing a value 
print("the numpy arrray = ",arr)

the set values =  {32, 34, 67, 85, 12, 15}
the numpy arrray =  {32, 34, 67, 85, 12, 15}


In [43]:
# from dict we are making to numpy array 
import numpy as np 

dict_keys = {'a': 1, 'b': 2, 'c': 3}
print(dict_keys)
array_from_keys = np.array(list(dict_keys.keys()))
print(array_from_keys)

{'a': 1, 'b': 2, 'c': 3}
['a' 'b' 'c']


In [44]:
# from dict we are making to numpy array 
import numpy as np 

dict_keys = {'a': 1, 'b': 2, 'c': 3}
print(dict_keys)
array_from_keys = np.array(list(dict_keys.values()))
print(array_from_keys)

{'a': 1, 'b': 2, 'c': 3}
[1 2 3]


# changing row or colum vectors 


In [56]:
#However, if you want to explicitly convert it to a row or column vector, you can use the reshape method. For example:
#now its dimension will be 2 
import numpy as np

a = [12, 15, 34, 67, 32, 85]
print("Original array:")
print(arr)

#convert to np array
arr = np.array(a)

# Convert to a row vector
row_vector = arr.reshape(1, -1)
print("\nRow vector:")
print(row_vector)
print(type(row_vector))
print(row_vector.ndim) #print the dimension of numpy array 
print(row_vector.shape) #print the shape of array (row,columns) in tuple format
print(row_vector.size) # print total number of elements present in array 


Original array:
20

Row vector:
[[12 15 34 67 32 85]]
<class 'numpy.ndarray'>
2
(1, 6)
6


In [58]:
#However, if you want to explicitly convert it to a row or column vector, you can use the reshape method. For example:
#now its dimension will be 2 
import numpy as np

a = [12, 15, 34, 67, 32, 85]
print("Original array:")
print(arr)

#convert to np array
arr = np.array(a)

# Convert to a row vector
row_vector = arr.reshape(-1, 1)
print("column vector:")
print(row_vector)
print(type(row_vector))
print(row_vector.ndim) #print the dimension of numpy array 
print(row_vector.shape) #print the shape of array (row,columns) in tuple format
print(row_vector.size) # print total number of elements present in array 


Original array:
[12 15 34 67 32 85]
column vector:
[[12]
 [15]
 [34]
 [67]
 [32]
 [85]]
<class 'numpy.ndarray'>
2
(6, 1)
6


# indexing and slice arrays 

In [66]:
#Creating sample array 
#array starts with 0 and ends with n-1

import numpy as np 

arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
#indexing 
print(arr[4])
print(arr[-1])
print(arr[0])


4
10
0


In [68]:
#slicing 
import numpy as np 

b = [12, 15, 34, 67, 32, 85,88,78,56,45,34,32,56]

a=np.array(b)

print(a[:])

[12 15 34 67 32 85 88 78 56 45 34 32 56]


In [69]:
print(a[2:])

[34 67 32 85 88 78 56 45 34 32 56]


In [70]:
print(a[2:8])

[34 67 32 85 88 78]


In [71]:
print(a[:8])

[12 15 34 67 32 85 88 78]


In [72]:
print(a[1:8:2])

[15 67 85 78]


In [73]:
print(a[-5:-2])

[56 45 34]


In [74]:
print(a[::-1])

[56 32 34 45 56 78 88 85 32 67 34 15 12]


# 3  matrix

In [76]:
#create 3X3 matrix with np.array()
import numpy as np 

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [79]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [80]:
# Getting individual element value
arr_2d[1,0]

20

In [81]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [82]:
#Set up matrix
arr2d = np.zeros((10,10))

In [83]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
arr2d.shape

(10, 10)

In [85]:
#Length of array
arr_length = arr2d.shape[1]

In [86]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [87]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [88]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [89]:
#creating 3 dimension using np.zeros()
import numpy as np

# Creating a 3-dimensional matrix filled with zeros
shape = (3, 3, 4)  # Specify the size of each dimension
matrix = np.zeros(shape)

print(matrix)
print("\nthe type of matix is =",type(matrix).__name__)
print("the matrix dimension is = ",matrix.ndim) #print the dimension of numpy array 
print("matrix shape in tuple = ",matrix.shape) #print the shape of array (row,columns) in tuple format
print("elements present in matrix is = ",matrix.size) # print total number of elements present in array 

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

the type of matix is = ndarray
the matrix dimension is =  3
matrix shape in tuple =  (3, 3, 4)
elements present in matrix is =  36


# creating higher dimension 


In [90]:
#creating a 5 dimension array 
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [91]:
#creating a 5 dimension array 
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=4)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[1 2 3 4]]]]
number of dimensions : 4


# broadcasting 

In [96]:
#example2 

import numpy as np

# Creating two arrays of different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([10, 20, 30])

# Performing an operation between arrays of different shapes
result = array1 + array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nResult of addition:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[10 20 30]

Result of addition:
[[11 22 33]
 [14 25 36]]


In [101]:
#example2

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
#print(arr.shape)

arr[5:]=120

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[  1   2   3   4   5 120 120 120 120 120 120 120]


# copy vs view 

In [97]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Creating a copy of the array
arr_copy = arr.copy()

# Modifying the copy
arr_copy[0] = 100

print("Original array:", arr)
print("Copy of the array (after modification):", arr_copy)


Original array: [1 2 3 4 5]
Copy of the array (after modification): [100   2   3   4   5]


In [98]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Creating a view of the array
arr_view = arr.view()

# Modifying the view
arr_view[0] = 100

print("Original array (after modification through view):", arr)
print("View of the array (after modification):", arr_view)


Original array (after modification through view): [100   2   3   4   5]
View of the array (after modification): [100   2   3   4   5]


In [99]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Creating a view of the array
arr_view = arr

# Modifying the view
arr_view[0] = 100

print("Original array (after modification through view):", arr)
print("View of the array (after modification):", arr_view)


Original array (after modification through view): [100   2   3   4   5]
View of the array (after modification): [100   2   3   4   5]
