# placeholders

In [1]:

#array: Create an array from a Python list or tuple.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [3]:
#zeros: Create an array filled with zeros.

zeros_arr = np.zeros((3, 3))  # Creates a 3x3 array filled with zeros
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# zeros_like: Create an array of zeros with the same shape and type as a given array.

arr = np.array([[1, 2, 3], [4, 5, 6]])

zeros_like_arr = np.zeros_like(arr)

print(zeros_like_arr)

[[0 0 0]
 [0 0 0]]


In [6]:
#ones: Create an array filled with ones.

ones_arr = np.ones((2, 2))  # Creates a 2x2 array filled with ones
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [7]:
#ones_like: Create an array of ones with the same shape and type as a given array.
arr = np.array([[1, 2], [3, 4]])
ones_like_arr = np.ones_like(arr)
print(ones_like_arr)

[[1 1]
 [1 1]]


In [11]:
#empty: Create an uninitialized array (values are not set).

empty_arr = np.empty((2, 2))  # Creates a 2x2 uninitialized array
print(empty_arr)

[[1. 1.]
 [1. 1.]]


In [12]:
#empty_like: Create an uninitialized array with the same shape and type as a given array.
arr = np.array([[1, 2], [3, 4]])
empty_like_arr = np.empty_like(arr)
print(empty_like_arr)

[[1667689040        611]
 [         0          0]]


## arange function 

In [15]:
#arange: Create an array with evenly spaced values within a specified range.
#arange(start,stop-1,step)

arange_arr = np.arange(10) 
print(arange_arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
arange_arr = np.arange(2, 10) 
print(arange_arr)

[2 3 4 5 6 7 8 9]


In [17]:
arange_arr = np.arange(2,10,2) 
print(arange_arr)

[2 4 6 8]


In [18]:
arange_arr = np.arange(10,2,-1) 
print(arange_arr)

[10  9  8  7  6  5  4  3]


## linspace function

In [19]:
#linspace: Create an array with evenly spaced values over a specified range.

linspace_arr = np.linspace(0, 1, 5)  
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
linspace_arr = np.linspace(5,10)  #if step not mention default is 50 
print(linspace_arr)
print(len(linspace_arr))

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]
50


## random number generation 


In [23]:
#random.Generator.random: Create an array of random values from a uniform distribution.
import numpy as np 
rng = np.random.default_rng()
random_arr = rng.random((5, 5))  # Creates a 2x2 array of random values between 0 and 1
print(random_arr)

[[0.22162522 0.27289122 0.88069602 0.07950712 0.38247723]
 [0.58973408 0.54507975 0.97270056 0.73702506 0.40536372]
 [0.1883711  0.92563191 0.72920029 0.82139781 0.18952368]
 [0.96337479 0.40797436 0.51161487 0.91669249 0.55400151]
 [0.58291189 0.37046845 0.40384056 0.30868453 0.96534453]]


In [24]:
#random.Generator.random: Create an array of random values from a uniform distribution.
import numpy as np 
rng = np.random.default_rng()
random_arr = rng.random(10)  # Creates a 2x2 array of random values between 0 and 1
print(random_arr)

[0.72248222 0.56639195 0.37629181 0.16783484 0.79956031 0.29529262
 0.15847312 0.22914877 0.18829527 0.82493564]


In [25]:
#random.Generator.normal: Create an array of random values from a normal (Gaussian) distribution.

import numpy as np 

random_normal_arr = rng.normal(0, 1, (2, 2))  # Creates a 2x2 array of random values from a normal distribution
print(random_normal_arr)

[[ 2.25128616  0.77369515]
 [-0.27371039  0.08662521]]


In [26]:
#random.Generator.normal: Create an array of random values from a normal (Gaussian) distribution.

import numpy as np 

random_normal_arr = rng.normal(5, 10, (2, 2))  # Creates a 2x2 array of random values from a normal distribution
print(random_normal_arr)

[[ 2.97724293  5.01580916]
 [-0.62982233  8.06626132]]


In [27]:
#random.Generator.normal: Create an array of random values from a normal (Gaussian) distribution.

import numpy as np 

random_normal_arr = rng.normal(5, 10, 5)  # Creates a 2x2 array of random values from a normal distribution
print(random_normal_arr)

[  9.1965057    6.62044764  14.96974405  19.92568505 -10.55055421]


In [28]:
#random.Generator.normal: Create an array of random values from a normal (Gaussian) distribution.

import numpy as np 

random_normal_arr = rng.normal(5, 10)  # Creates a 2x2 array of random values from a normal distribution
print(random_normal_arr)

16.325510232465298


In [29]:
#random.Generator.normal: Create an array of random values from a normal (Gaussian) distribution.

import numpy as np 

random_normal_arr = rng.normal(5)  # Creates a 2x2 array of random values from a normal distribution
print(random_normal_arr)

3.4293696379076666


In [32]:
np.random.randint(1,10,10)

array([1, 3, 4, 4, 6, 9, 4, 2, 3, 8])

In [33]:
np.random.rand(1,10,10) #(1X10X10)

array([[[0.45424086, 0.78382656, 0.90857554, 0.14082547, 0.24608019,
         0.1045754 , 0.73583007, 0.9327859 , 0.78136422, 0.86722413],
        [0.85463708, 0.77226121, 0.73799356, 0.77020499, 0.67792002,
         0.84403463, 0.45440774, 0.77874524, 0.33717599, 0.9176172 ],
        [0.2558183 , 0.4829354 , 0.42798568, 0.08317151, 0.68826847,
         0.26217651, 0.95020405, 0.02058158, 0.62934299, 0.87115481],
        [0.73563851, 0.12794486, 0.19056412, 0.03972562, 0.91538974,
         0.50732932, 0.29601342, 0.95848959, 0.79618055, 0.46167148],
        [0.42792822, 0.14777514, 0.48376156, 0.93375319, 0.30664413,
         0.8990526 , 0.26438428, 0.14560622, 0.86953118, 0.10018672],
        [0.9240535 , 0.638587  , 0.84367892, 0.99560585, 0.74151636,
         0.44539508, 0.44736402, 0.90501562, 0.76380952, 0.60321938],
        [0.149786  , 0.76249087, 0.24040746, 0.9777548 , 0.83220119,
         0.87938826, 0.97597895, 0.0592753 , 0.44079012, 0.54828598],
        [0.86914413, 0.2906

##  from function 

In [41]:
import numpy as np

# Define a function that takes two arguments (indices) and returns a value based on those indices
def my_func(x, y):
    return 3 * x + y

# Create a 3x3 array using fromfunction with the defined function
result_arr = np.fromfunction(my_func, (3, 3))

print(result_arr)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [36]:
#fromfunction: Construct an array by executing a function over each coordinate.

def my_func(x, y):
    return x + y

from_func_arr = np.fromfunction(my_func, (3, 3))
print(from_func_arr)

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


In [40]:
#fromfunction: Construct an array by executing a function over each coordinate.
import numpy as np

def my_func(x, y):
    return x + y

a = [1, 2, 3, 4]
b = [1, 2, 3, 4]

a = np.array(a)
b = np.array(b)

# Create coordinate arrays using meshgrid
x, y = np.meshgrid(a, b)

# Use fromfunction with coordinate arrays
from_func_arr = np.fromfunction(my_func, (len(a), len(b)))

print(from_func_arr)


[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


In [42]:
#eye: Create a 2-D array with ones on the diagonal and zeros elsewhere (identity-like).

import numpy as np

eye_arr = np.eye(3)  # Create a 3x3 identity matrix
print(eye_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#identity: Create a square identity matrix of given size.

identity_arr = np.identity(4)  # Create a 4x4 identity matrix
print(identity_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [44]:
#logspace: Return numbers spaced evenly on a logarithmic scale.

logspace_arr = np.logspace(1, 3, num=5)  # Create an array of 5 numbers spaced evenly on a log scale between 10^1 and 10^3
print(logspace_arr)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [45]:
#mgrid: Create a dense multi-dimensional "meshgrid".

x, y = np.mgrid[0:3, 0:3]  # Create a meshgrid of points from (0,0) to (2,2) in 2D
print(x)
print(y)

[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [46]:
#ogrid: Create an open multi-dimensional "meshgrid".

x, y = np.ogrid[0:3, 0:3]  # Create an open meshgrid of points from (0,0) to (2,2) in 2D
print(x)
print(y)

[[0]
 [1]
 [2]]
[[0 1 2]]


In [47]:
#r_: Translates slice objects to concatenation along the first axis.

concatenated_arr = np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]  # Concatenate two arrays along the first axis
print(concatenated_arr)

[1 2 3 4 5 6]


# input and output 

In [53]:

import numpy as np

from_file_arr = np.loadtxt('data.txt', dtype=int)
print(from_file_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [54]:
import numpy as np

# Create a large NumPy array
large_array = np.random.rand(10, 10)

# Save the array to a file
np.save('large_array.npy', large_array)

# Load the array from the saved file
loaded_array = np.load('large_array.npy')

# Print the loaded array
print("Loaded array:")
print(loaded_array)


Loaded array:
[[0.07640039 0.51539889 0.03685021 0.21889739 0.6434532  0.40082429
  0.48827955 0.33156387 0.78404492 0.24472112]
 [0.70690041 0.23953858 0.61210588 0.90952303 0.88197293 0.10694115
  0.96779901 0.3189961  0.58449192 0.0114859 ]
 [0.67279532 0.77660412 0.56155858 0.66986892 0.24905727 0.12958735
  0.1528416  0.03546236 0.95422942 0.60306131]
 [0.51530804 0.01530335 0.91627201 0.42084975 0.97376889 0.42931428
  0.16722209 0.43669262 0.12799044 0.27616721]
 [0.83023749 0.8383276  0.6165107  0.30969007 0.98460079 0.56479701
  0.81335236 0.12614477 0.28255125 0.34946222]
 [0.16728767 0.77880231 0.41734731 0.95213237 0.24715688 0.06403557
  0.80947934 0.26803349 0.42882108 0.63496787]
 [0.09585329 0.26218204 0.67398896 0.0502287  0.91124149 0.84696732
  0.81713072 0.71424892 0.45255466 0.2212797 ]
 [0.71887949 0.90903988 0.86978169 0.95472756 0.86892937 0.31203109
  0.60033897 0.51702105 0.34264894 0.30686432]
 [0.78522739 0.35312923 0.76835883 0.43394556 0.22654824 0.9399333

# np.savez

In [55]:
import numpy as np

# Create two NumPy arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Save the arrays to a `.npz` file
np.savez('array.npz', a=a, b=b)


In [56]:
import numpy as np

# Load the arrays from the saved file
loaded_data = np.load('array.npz')

# Extract the arrays from the loaded data
loaded_a = loaded_data['a']
loaded_b = loaded_data['b']

# Print the loaded arrays
print("Loaded array a:")
print(loaded_a)
print("Loaded array b:")
print(loaded_b)


Loaded array a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Loaded array b:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [57]:
#csv file 

import numpy as np

# Create some data
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Save the data to a CSV file
np.savetxt('my_file.csv', data, delimiter=',')


In [58]:
import numpy as np

# Load the data from the CSV file
loaded_data = np.genfromtxt("my_file.csv", delimiter=',')

# Print the loaded data
print("Loaded data:")
print(loaded_data)


Loaded data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
